CBL/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('', include('core.urls')),
    path('projects/', include('projects.urls')),
    path('browse/', include('browse.urls')),
    path("admin/", admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

browse/urls.py
from django.urls import path

from . import views



app_name = 'browse'

urlpatterns = [
    path('', views.index, name='index'),
    #path('', views.index, name='category'),
]

core/urls.py
from django.urls import path, include

from . import views

app_name = 'core'

urlpatterns = [
    path('', views.index, name='index'),
    path('services/', views.services, name='services'),
    path('browse/', include('browse.urls')),
    path('commission/', views.commission, name='commission'),
]

projects/urls.py
from django.urls import path, include

from . import views

app_name = 'projects'

urlpatterns = [
    path('', views.projects, name='projects'),
    path('browse/', include('browse.urls')),
    path('new/', views.new, name='new'),
    path('<int:pk>/', views.detail, name='detail'),
    path('<int:pk>/edit/', views.edit, name='edit'),
]

core/models.py
from django.db import models

core/forms.py
from django import forms

from projects.models import Category, Project, Service, ServiceRequest


INPUT_CLASSES = 'w-full py-4 px-6 rounded-xl border'


class ServiceForm(forms.ModelForm):
    class Meta:
        model = ServiceRequest
        fields = ('subject','email', 'message')

        widgets = {
            'subject': forms.TextInput(attrs={
                'class': INPUT_CLASSES
            }),

            'email': forms.EmailInput(attrs={
                'class': INPUT_CLASSES
            }),
            'message': forms.Textarea(attrs={
                'class': INPUT_CLASSES
            }),

        }

core/views.py
from django.shortcuts import render,redirect
from django.template.loader import render_to_string
from django.core.mail import send_mail
from django.conf import settings

from projects.models import Category, Project, Service, ServiceRequest

from .forms import ServiceForm

def index(request):
    projects = Project.objects.filter(invisible=False)[0:3]
    categories = Category.objects.all()

    return render(request, 'core/index.html', {
        'categories': categories,
        'projects': projects,
    })

def commission(request):
    services = Service.objects.all()


    return render(request, 'core/commission.html', {
        'services': services
    })

def services(request):
    if request.method == 'POST':
        form = ServiceForm(request.POST)

        if form.is_valid():
            subject = form.cleaned_data['subject']
            message = form.cleaned_data['message']
            email = form.cleaned_data['email']
            html = render_to_string('core/servicerequest.html',{
                'email' : email,
                'message': message,
                'subject': subject
            })
            send_mail(subject,message,email,['circuitboredlab@gmail.com'],html_message=html)
            return redirect('/')
        else:
            print('is not valid')
            form = ServiceForm()
        message_subject = request.POST['message-subject']
        message_email = request.POST['message-email']
        message = request.POST['message']

        send_mail(
            subject,# subject
            message, #message
            message_email, #from email
            ['circuitboredlab@gmail.com'], #To email
        )
    form = ServiceForm()

    return render(request, 'core/services.html',{
        'form':form,
    })

core/templates/core/base.html
<!doctype html>

<html>
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">

        <script src="https://cdn.tailwindcss.com"></script>

        <title>{% block title %}{% endblock %} | Circuit Bored</title>
    </head>

    <body class="bg-auto bg-green-800 flex flex-col min-h-screen">
        <nav class="py-2 px-2 flex justify-between bg-black items-center border-b border-gray-200">
            <a href="{% url 'browse:index' %}">
                <img src="https://raw.githubusercontent.com/enzosupreme/cbl-images/main/logo.png"
                class="pr-5 object-scale-down h-20 w-40"/>
                </a>
            <ul class="md:flex md:items-center md:w-auto">
                <li class="mx-4 my-6 md:my-0">
                    <a href="/" class="text-center text-sm md:text-md lg:text-lg font-semibold text-yellow-500 hover:text-white">Circuit Bored</a>
                </li>
            </ul>

            <ul class="md:flex md:items-center md:w-auto">
                <li class="mx-4 my-6 md:my-0">
                    <a href="{% url 'browse:index' %}" class="text-sm md:text-md lg:text-lg font-semibold text-yellow-700 hover:text-white">Projects</a>
                </li>
                <li class="mx-4 my-6 md:my-0">
                    <a href="{% url 'core:commission' %}" class="text-sm md:text-md lg:text-lg font-semibold text-yellow-700 hover:text-white">Commission</a>
                </li>
                <li class="mx-4 my-6 md:my-0">
                    <a href="https://circuitboredlab.etsy.com" class="px-6 py-3 text-sm sm:text-md lg:text-lg font-semibold bg-green-700 text-white rounded-xl hover:bg-yellow-500">Shop</a>
                </li>
            </ul>

        </nav>
        <div class="px-6 py-6">
            {% block content %}
            {% endblock %}
        </div>

        <footer class="py-6 px-6 flex justify-between bg-purple-900 mt-auto">
            <div class="w-2/3 pr-10 py-5">
                <h3 class="mb-5 font-semibold text-green-700 hover:text-yellow-700"></h3>

                <a href="{% url 'core:services' %}" class="pt-10 text-s text-green-800 hover:text-yellow-800">circuitboredlab@gmail.com</a>
            </div>

            <div class="w-6/9 pt-9 pr-2">
                    <a href="{% url 'browse:index' %}" class="justify-center items-center">
                    <img src="https://raw.githubusercontent.com/enzosupreme/cbl-images/main/logo.png"
                    class="h-10 w-10">
                    </a>
                </h3>
            </div>

            <div class="w-1/9">
                <ul class="space-y-2">
                    <li><a href="https://github.com/enzosupreme/" class="text-s text-purple-400 hover:text-yellow-500">Github</a></li>
                    <li><a href="https://www.instagram.com/circuitboredlab/" class="text-s text-purple-400 hover:text-yellow-500">Instagram</a></li>
                    <li><a href="https://www.youtube.com/channel/UCCEIhKijXbmY8ajvEMQeXsw/" class="text-s text-purple-400 hover:text-yellow-500">Youtube</a></li>
                    <li><a href="https://x.com/CircuitBoredLab?t=5E3CiOdZE1bWFomF7Cq2Tw&s=09" class="text-s text-purple-400 hover:text-yellow-500">twitter|x</a></li>
                </ul>
            </div>

        </footer>

    </body>

</html>

core/templates/core/commission.html
{% extends 'core/base.html' %}

{% block title %}Commission{% endblock %}
{% block content %}

<div class="mt-6 px-6 py-4 bg-green-800 rounded-xl">
        <h2 class="mb-6 text-2xl text-center text-yellow-500">Services</h2>

        <div class="grid grid-cols-1 gap-3">
            {% for service in services %}
            <div>
                    <div class="p-12 bg-green-700 hover:bg-green-900 rounded-xl">
                        <a href="{% url 'core:services' %}">
                            <h2 class="text-2xl text-center text-white hover:text-yellow-500">{{ service.name }}</h2>

                        </a>

                    </div>

            </div>
            {% endfor %}
        </div>

    </div>
{% endblock %}

core/templates/core/index.html
{% extends 'core/base.html' %}

{% block title %}Welcome{% endblock %}
{% block content %}

    <div class="px-6 py-10 bg-green-900 rounded-xl">
        <h2 class="mb-8 text-2xl pr-6 text-center text-yellow-500">Recent Projects</h2>

        <form method="get" action="{% url 'browse:index' %}">
            </form>

        <div class="grid grid-cols-3 gap-3">
            {% for project in projects %}
            <div>
                <a href="{% url 'projects:detail' project.id %}">
                    <div>
                        <img src="{{ project.image.url }}" class=" object-fill rounded-t-xl">
                    </div>

                    <div class="p-3 bg-yellow-600 rounded-b-xl">
                        <h2 class="text-sm sm:text-md lg:text-lg text-white">{{ project.name }}</h2>
                    </div>
                </a>
            </div>
            {% endfor %}
        </div>
    </div>

    <div class="mt-6 px-6 py-4 bg-green-800 rounded-xl">
        <h2 class="mb-12 text-sm sm:text-md lg:text-lg text-center text-white hover:text-purple-700">Project Type</h2>

        <div class="grid grid-cols-3 gap-3">
            {% for category in categories %}
            <div>
                    <div class="p-3 bg-black rounded-xl">
                        <a href="{% url 'browse:index' %}?query={{ query }}&category={{ category.id }}">
                            <h2 class="text-xs sm:text-s lg:text-lg xl:text-xl text-white hover:text-purple-700">{{ category.name }}</h2>
                            <p class=" text-xs sm:text-s lg:text-lg xl:text-xl text-purple-500"> {{ category.projects.count }} projects</p>

                        </a>

                    </div>

            </div>
            {% endfor %}
        </div>

    </div>
{% endblock %}

core/templates/core/servicerequest.html
<h2> Service request submission</h2>

<p><b>Subject: </b>{{ subject }}</p>
<p><b>E-mail:</b>{{ email }}</p>
<p><b>Message:</b>{{ message }}</p>

core/templates/core/services.html
{% extends 'core/base.html' %}

{% block title %}{{ title }}{% endblock %}


{% block content %}
<h1 class="mb-6 text-3xl">{{ title }}</h1>

<form method="POST" action=".">
    {% csrf_token %}
    <div class="space-y-4">
        {{ form.as_p }}
    </div>

    {% if form.errors or form.non_field.errors %}
    <div class="mb-3 p-6 bg-red-100 rounded-xl">
        {% for field in form %}
            {{ field.errors }}
        {% endfor %}

        {{ form.non_field_errors }}
    </div>
    {% endif %}
    <button class="py-4 px-8 text-lg bg-white hover:bg-red-900 rounded-xl">Send</button>
</form>
{% endblock %}