CBL/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('', include('core.urls')),
    path('projects/', include('projects.urls')),
    path('browse/', include('browse.urls')),
    path("admin/", admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

browse/urls.py
from django.urls import path

from . import views



app_name = 'browse'

urlpatterns = [
    path('', views.index, name='index'),
    #path('', views.index, name='category'),
]

projects/urls.py
from django.urls import path, include

from . import views

app_name = 'projects'

urlpatterns = [
    path('', views.projects, name='projects'),
    path('browse/', include('browse.urls')),
    path('new/', views.new, name='new'),
    path('<int:pk>/', views.detail, name='detail'),
    path('<int:pk>/edit/', views.edit, name='edit'),
]

projects/models.py
from django.contrib.auth.models import User
from django.db import models

class Category(models.Model):
    name = models.CharField(max_length=255)

    class Meta:
        ordering = ('name',)
        verbose_name_plural = 'Categories'

    def __str__(self):
        return self.name

class Service(models.Model):
    name = models.CharField(max_length=255)

    class Meta:
        ordering = ('name',)
        verbose_name_plural = 'Services'

    def __str__(self):
        return self.name

class ServiceRequest(models.Model):
    subject = models.CharField(max_length=255, null=True, blank=True)
    email = models.EmailField(max_length=255)
    message = models.TextField(blank=True, null=True)

class Project(models.Model):
    category = models.ForeignKey(Category, related_name='projects', on_delete=models.CASCADE)
    name = models.CharField(max_length=255)
    description = models.TextField(blank=True, null=True)
    image = models.ImageField(upload_to='project_images', blank=True, null=True)
    created_at = models.DateTimeField(auto_now_add=True)
    invisible = models.BooleanField(default=False)
    github = models.URLField(max_length=200, blank=True, null=True)
    youtube = models.URLField(max_length=200, blank=True, null=True)
    shop = models.URLField(max_length=200, blank=True, null=True)

    def __str__(self):
        return self.name

projects/forms.py
from django import forms

from .models import Project

INPUT_CLASSES = 'w-full py-4 px-6 rounded-xl border'

class NewProjectForm(forms.ModelForm):
    class Meta:
        model = Project
        fields = ('category', 'name','description', 'image',)

        widgets = {
            'category': forms.Select(attrs={
                'class': INPUT_CLASSES
            }),
            'name': forms.TextInput(attrs={
                'class': INPUT_CLASSES
            }),
            'description': forms.Textarea(attrs={
                'class': INPUT_CLASSES
            }),
            'image': forms.FileInput(attrs={
                'class': INPUT_CLASSES
            }),
        }




class EditProjectForm(forms.ModelForm):
    class Meta:
        model = Project
        fields = ('category', 'name','description', 'image',)

        widgets = {
            'category': forms.Select(attrs={
                'class': INPUT_CLASSES
            }),
            'name': forms.TextInput(attrs={
                'class': INPUT_CLASSES
            }),
            'description': forms.Textarea(attrs={
                'class': INPUT_CLASSES
            }),
            'image': forms.FileInput(attrs={
                'class': INPUT_CLASSES
            }),
        }

projects/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, get_object_or_404, redirect
from django.db.models import Q

from .forms import NewProjectForm, EditProjectForm
from .models import Project, Category

def detail(request, pk):
    projects = get_object_or_404(Project, pk=pk)
    related_projects = Project.objects.filter(category=projects.category).exclude(pk=pk)[0:3]


    return render(request, 'projects/detail.html', {
        'projects': projects,
        'related_projects': related_projects
    })

def Categories(request,pk):
    projects = get_object_or_404(Project, pk=pk)
    category = Project.objects.filter(category=projects.category)
    query = request.Get.get('query', category.name)

    return render(request, 'projects/projects.html', {
        'projects': projects,
        'category': category,
        'query' : query,
    })


def projects(request):
    query = request.Get.get('query', projects.category)
    category_id = request.GET('category', 0)
    projects = Project.object.filter(invisible=False)
    categories = Category.objects.all()

    if category_id:
        projects = projects.filter(category_id=category_id)
    if query:
        projects = projects.filter(Q(name__icontains=query) | Q(description__icontains=query))
    return render(request, 'projects/projects.html', {
        'projects': projects,
        'query':query,
        'category':category,
        'category_id': int(category_id)
    })

@login_required
def new(request):
    if request.method == 'POST':
        form = NewProjectForm(request.POST, request.FILES)

        if form.is_valid():
            projects = form.save(commit=False)
            projects.created_by = request.user
            projects.save()

            return redirect('projects:detail', pk=projects.id)

    else:
        form = NewProjectForm()

    return render(request, 'projects/form.html', {
        'form': form,
        'title': 'New Project'
    })

@login_required
def edit(request, pk):
    projects = get_object_or_404(Project, pk=pk)

    if request.method == 'POST':
        form = EditProjectForm(request.POST, request.FILES, instance=projects)

        if form.is_valid():
            projects = form.save(commit=False)
            projects.created_by = request.user
            projects.save()

            return redirect('projects:detail', pk=projects.id)

    else:
        form = EditProjectForm(instance=projects)

    return render(request, 'projects/form.html', {
        'form': form,
        'title': 'Edit Project'
    })

projects/templates/projects/category.html
{% extends 'core/base.html' %}

{% block title %}{{ category.name }}{% endblock %}
{% block content %}
    <div class="mt-6 px-6 py-12 bg-green-900 rounded-xl">
        <a href="/">
        <h2 class="mb-12 text-2xl pr-10 text-center text-yellow-500">{{ category.name }}</h2>
        </a>
        <div class="grid grid-cols-3 gap-3">
            {% for project in category %}
            <div>
                <a href="{% url 'projects:detail' project.id %}">
                    <div>
                        <img src="{{ project.image.url }}" class="object-contain rounded-t-xl">
                    </div>

                    <div class="p-6 bg-yellow-600 rounded-b-xl">
                        <h2 class="text-2xl text-white">{{ project.name }}</h2>
                    </div>
                </a>
            </div>
            {% endfor %}
        </div>
    </div>


{% endblock %}

projects/templates/projects/detail.html
{% extends 'core/base.html' %}

{% block title %}{{ projects.name }}{% endblock %}

{% block content %}
<form method="get" action="{% url 'browse:index' %}">
    <div class="p-6 bg-green-900 rounded-xl">
        <div class=" grid h-100 w-100 gap-6 p-3">

        <a href="{% url 'browse:index' %}">
        <h1 class="mb-6 text-xs sm:text-md lg:text-lg xl:text-xl text-yellow-500 hover:text-yellow-700">{{ projects.name }}</h1>

            <div class="col-span-3">
            <img src="{{ projects.image.url }}" class="rounded-xl">
            </div>
            <strong class="text-yellow-800">Project Log:</strong><br>
        <p class="pl-3 text-white text-center justify-center items-center">
            {{ projects.description  }}
        </p>
        </a>
        <br>
            <div class="grid grid-cols-2 space-x-3">
            {% if projects.github %}
                <a href="{{ projects.github }}" class="inline-block mt-6 px-2 py-3 text-xs sm:text-md lg:text-lg xl:text-xl font-semibold bg-contain bg-teal-700 text-white text-center rounded-xl hover:bg-teal-800 ">Github</a>
            {% endif %}
            {% if projects.youtube %}
                <a href="{{ projects.youtube }}" class="inline-block mt-6 py-3 text-xs sm:text-md lg:text-lg xl:text-xl font-semibold bg-contain bg-red-700 text-white text-center rounded-xl hover:bg-red-800">Youtube</a>
            {% endif %}
            {% if projects.shop %}
                <a href="{{ projects.shop }}" class="inline-block mt-6 px-2 py-3 text-xs sm:text-md lg:text-lg xl:text-xl font-semibold bg-contain bg-purple-900 text-white text-center rounded-xl hover:bg-purple-700">Buy</a>
            {% endif %}
            </div>
        <br></br>
        <p class=" text-purple-900"><strong>Posted: </strong>{{ projects.created_at }}</p>
            </div>
</div>
</form>

 <div class="mt-6 px-6 py-12 bg-green-900 rounded-xl">
      <a href="{% url 'browse:index' %}?query={{ query }}&category={{ projects.category.id }}">
        <h2 class="mb-12 text-xs sm:text-md lg:text-lg xl:text-xl text-center text-yellow-500">More {{ projects.category }}</h2>
      </a>
        <div class="grid grid-cols-3 gap-3">
            {% for project in related_projects %}
            <div>
                <a href="{% url 'projects:detail' project.id %}">
                    <div>

                        <img src="{{ project.image.url }}" class="rounded-t-xl">
                    </div>

                    <div class="p-2 bg-yellow-600 rounded-b-xl">
                        <h2 class="text-xs sm:text-md lg:text-lg xl:text-xl text-white">{{ project.name }}</h2>
                    </div>
                </a>
            </div>
            {% endfor %}
        </div>
    </div>
{% endblock %}

projects/templates/projects/form.html
{% extends 'core/base.html' %}

{% block title %}{{ title }}{% endblock %}


{% block content %}
<h1 class="mb-6 text-3xl">{{ title }}</h1>

<form method="POST" action="." enctype="multipart/form-data">
    {% csrf_token %}

    <div class="space-y-4">
        {{ form.as_p }}
    </div>

    {% if form.errors or form.non_field.errors %}
    <div class="mb-3 p-6 bg-red-100 rounded-xl">
        {% for field in form %}
            {{ field.errors }}
        {% endfor %}

        {{ form.non_field_errors }}
    </div>
    {% endif %}
    <button class="py-4 px-8 text-lg bg-red-700 hover:bg-red-900 rounded-xl">Submit</button>
</form>
{% endblock %}

projects/templates/projects/projects.html
{% extends 'core/base.html' %}

{% block title %}Category{% endblock %}

{%block content %}
    <div class="pb-6 grid-cols-4 gap-4 bg-gray-100">
        <div class="col-span-1">
            <form method="get" action="{% url 'projects:projects' %}">
                <input name="query" class="w-full py-4 px-6 border rounded-xl" type="text" value="{{ query }}" placeholder="Find a project">

                <buttton class="mt-2 py-4 px-8 text-lg bg-teal-500 text-white rounded-xl"></buttton>
            </form>
        </div>
    <div class="pb-6 grid grid-cols-4 gap-4">
        <div class="col-span-1">sidebar</div>


        <div class="grid grid-cols-3 gap-3">
            {% for project in projects %}
            <div>
                <a href="{% url 'projects:detail' project.id %}">
                    <div>
                        <img src="{{ project.image.url }}" class="rounded-t-xl">
                    </div>

                    <div class="p-6 bg-yellow-600 rounded-b-xl">
                        <h2 class="text-2xl text-white">{{ project.name }}</h2>
                    </div>
                </a>
            </div>
            {% endfor %}
        </div>
    </div>

    </div>
{% endblock %}